workflows:
  build-ios:
    name: Build iOS IPA
    environment:
      flutter: stable
      vars:
        API_KEY: $API_KEY  # Přidej si vlastní API_KEY proměnnou
    scripts:
      - name: Flutter Pub Get
        script: |
          flutter pub get

      - name: Generování .env souboru
        script: |
          echo "API_KEY=$API_KEY" > .env

      - name: Build iOS App (Release)
        script: |
          flutter build ios --release --no-codesign
      - name: Export IPA
        script: |
          cd build/ios/iphoneos
          xcrun -sdk iphoneos PackageApplication -v Runner.app -o $HOME/ipa/Runner.ipa

    artifacts:
      # Ukládáme IPA soubor jako artefakt
      - $HOME/ipa/Runner.ipa
