workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: 3.32.0-0.3.pre
      xcode: latest
      groups:
        - api
    scripts:
      - name: Vytvoření .env souboru
        script: |
          echo "API_KEY=$API_KEY" > code_sphere_app/.env
      - name: Flutter Pub Get
        script: |
          cd code_sphere_app
          flutter pub get

      - name: Flutter Build iOS
        script: |
          cd code_sphere_app
          flutter build ios --release --no-codesign
      - name: Zkontrolovat přítomnost Runner.app
        script: |
          cd code_sphere_app
          if [ -d "build/ios/iphoneos/Runner.app" ]; then
            echo "Soubor Runner.app existuje."
          else
            echo "Soubor Runner.app neexistuje."
            exit 1
          fi
      - name: Zabalit Runner.app do ZIP
        script: |
          echo "Zabaluji Runner.app do ZIP..."
          cd code_sphere_app
          zip -r build/ios/iphoneos/Runner.app.zip build/ios/iphoneos/Runner.app
      - name: Zkontrolovat, zda soubor existuje
        script: |
          cd code_sphere_app
          if [ -f "build/ios/iphoneos/Runner.app.zip" ]; then
            echo "Soubor ZIP existuje."
          else
            echo "Soubor ZIP neexistuje."
            exit 1
          fi
      - name: Uložení ZIP souboru
        script: |
          mv code_sphere_app/build/ios/iphoneos/Runner.app.zip $HOME/Runner.app.zip

      # Test API klíče
      - name: Test API klíče
        script: |
          echo "Testuji API klíč..."
          response=$(curl -s -w "%{http_code}" -H "Authorization: Bearer $API_KEY" \
            -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$API_KEY" \
            -d '{"contents":[{"parts":[{"text":"Testovací prompt."}]}]}')
          
          http_code=$(echo $response | tail -n1)
          if [ "$http_code" -eq 200 ]; then
            echo "API klíč je validní, odpověď je OK."
          else
            echo "Chyba API: Odpověď $http_code."
            exit 1
          fi

    artifacts:
      - $HOME/Runner.app.zip
