workflows:
  build-ios:
    name: Build iOS IPA
    environment:
      flutter: stable
      vars:
        API_KEY: $API_KEY  # Přidej si vlastní API_KEY proměnnou
    scripts:
      - name: Flutter Pub Get
        script: |
          cd code_sphere_app
          flutter pub get

      - name: Generování .env souboru
        script: |
          cd code_sphere_app
          echo "API_KEY=$API_KEY" > .env

      - name: Build iOS App (Release)
        script: |
          cd code_sphere_app
          flutter build ios --release --no-codesign

      - name: Export IPA
        script: |
          cd code_sphere_app/build/ios/iphoneos
          mkdir -p $CM_BUILD_DIR/ipa
          xcrun -sdk iphoneos PackageApplication -v Runner.app -o $CM_BUILD_DIR/ipa/Runner.ipa

    artifacts:
      - code_sphere_app/build/ios/iphoneos/Runner.app
      - $CM_BUILD_DIR/ipa/Runner.ipa