workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: 3.32.0-0.3.pre
      xcode: latest
      groups:
        - api
    scripts:
      - name: Vytvoř .env soubor
        script: |
          echo "API_KEY=$API_KEY" > code_sphere_app/.env
      - name: Flutter Pub Get
        script: |
          cd code_sphere_app
          flutter pub get
      - name: Flutter Build iOS
        script: |
          cd code_sphere_app
          flutter clean  # Tohle přidat může pomoct vyčistit cache
          flutter build ios --release --no-codesign
