workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: 3.32.0-0.3.pre
      xcode: latest
      groups:
        - api
    scripts:
      - name: Vytvoření .env souboru
        script: |
          echo "API_KEY=$API_KEY" > code_sphere_app/.env
      - name: Flutter Pub Get
        script: |
          cd code_sphere_app
          flutter pub get
      - name: Flutter Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Zabalit Runner.app do ZIP
        script: |
          zip -r build/ios/iphoneos/Runner.app.zip build/ios/iphoneos/Runner.app
      - name: Uložení ZIP souboru
        script: |
          mv build/ios/iphoneos/Runner.app.zip $HOME/Runner.app.zip