workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: 3.32.0-0.3.pre
      xcode: latest
      groups:
        - api
    scripts:
      - name: Vytvoření .env souboru
        script: |
          echo "API_KEY=$API_KEY" > code_sphere_app/.env
      - name: Flutter Pub Get
        script: |
          cd code_sphere_app
          flutter pub get
      - name: Flutter Build iOS
        script: |
          cd code_sphere_app
          flutter build ios --release --no-codesign
      - name: Zabalit Runner.app do ZIP
        script: |
          cd code_sphere_app
          zip -r build/ios/iphoneos/Runner.app.zip build/ios/iphoneos/Runner.app
      - name: Zkontrolovat, zda soubor existuje
        script: |
          if [ -f "build/ios/iphoneos/Runner.app.zip" ]; then
            echo "Soubor ZIP existuje."
          else
            echo "Soubor ZIP neexistuje."
            exit 1
          fi
      - name: Uložení ZIP souboru
        script: |
          mv build/ios/iphoneos/Runner.app.zip $HOME/Runner.app.zip
    artifacts:
      - $HOME/Runner.app.zip
    publishing:
      email:
        recipients:
          - name@example.com